from pydantic import BaseModel, Field
from typing import List

# The 10 canonical sections for a Board Story
BOARD_STORY_SECTIONS = [
    "executive_summary",
    "risk_posture",
    "governance_maturity",
    "control_effectiveness",
    "compliance_status",
    "financial_exposure",
    "threat_landscape",
    "resource_allocation",
    "remediation_roadmap",
    "strategic_recommendations"
]

class BoardStorySection(BaseModel):
    section_id: str = Field(..., description="Canonical section ID (e.g., 'executive_summary')")
    title: str = Field(..., description="Human readable title for the section")
    content: str = Field(..., description="Narrative prose for this section generated by LLM")

class BoardStory(BaseModel):
    sections: List[BoardStorySection] = Field(
        ...,
        min_length=10,
        max_length=10,
        description="Exactly 10 ordered narrative sections."
    )
