name: Bug Report
description: Report a reproducible issue in ResilAI
labels: ["type: bug", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please include enough detail for reproducibility.
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Short description of the issue
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Local
        - Staging
        - Production
    validations:
      required: true
