name: Feature Request
description: Suggest a feature for ResilAI
labels: ["type: feature", "status: triage"]
body:
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      placeholder: One sentence describing the request
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What user or business problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What should ResilAI do?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Investor, enterprise, or user impact
