"""Add Sentinel Models

Revision ID: 06057376e451
Revises: 47775d58103a
Create Date: 2026-05-31 00:08:44.220069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06057376e451'
down_revision: Union[str, Sequence[str], None] = '47775d58103a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentinel_simulations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('scenario_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('readiness_impact_score', sa.Float(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('missing_controls', sa.JSON(), nullable=True),
    sa.Column('simulation_context', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentinel_simulations', schema=None) as batch_op:
        batch_op.create_index('ix_simulation_org', ['org_id'], unique=False)
        batch_op.create_index('ix_simulation_scenario', ['scenario_type'], unique=False)

    op.create_table('telemetry_evidence',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('telemetry_verified', sa.Boolean(), nullable=False),
    sa.Column('control_domain', sa.String(length=100), nullable=True),
    sa.Column('framework_mapping', sa.String(length=100), nullable=True),
    sa.Column('raw_event_reference', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_reference'], ['telemetry_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_domain', ['control_domain'], unique=False)
        batch_op.create_index('ix_evidence_source', ['source'], unique=False)
        batch_op.create_index('ix_evidence_type', ['evidence_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_type')
        batch_op.drop_index('ix_evidence_source')
        batch_op.drop_index('ix_evidence_domain')

    op.drop_table('telemetry_evidence')
    with op.batch_alter_table('sentinel_simulations', schema=None) as batch_op:
        batch_op.drop_index('ix_simulation_scenario')
        batch_op.drop_index('ix_simulation_org')

    op.drop_table('sentinel_simulations')
    # ### end Alembic commands ###
