"""Add verification engine models

Revision ID: 47775d58103a
Revises: 9417dc27ed92
Create Date: 2026-05-29 23:35:28.216606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47775d58103a'
down_revision: Union[str, Sequence[str], None] = '9417dc27ed92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_results',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('VERIFIED', 'PARTIAL', 'SELF_ATTESTED', 'NOT_VERIFIED', name='verificationstate'), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='verificationconfidence'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_organization_id'), ['organization_id'], unique=False)

    op.create_table('verification_audit_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('previous_state', sa.Enum('VERIFIED', 'PARTIAL', 'SELF_ATTESTED', 'NOT_VERIFIED', name='verificationstate'), nullable=True),
    sa.Column('new_state', sa.Enum('VERIFIED', 'PARTIAL', 'SELF_ATTESTED', 'NOT_VERIFIED', name='verificationstate'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_audit_logs_verification_result_id'), ['verification_result_id'], unique=False)

    op.create_table('control_evidence',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_result_id', sa.CHAR(length=36), nullable=False),
    sa.Column('telemetry_event_id', sa.CHAR(length=36), nullable=True),
    sa.Column('connector_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telemetry_event_id'], ['telemetry_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_evidence_verification_result_id'), ['verification_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_evidence_verification_result_id'))

    op.drop_table('control_evidence')
    with op.batch_alter_table('verification_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_audit_logs_verification_result_id'))

    op.drop_table('verification_audit_logs')
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_organization_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_control_id'))

    op.drop_table('verification_results')
    # ### end Alembic commands ###
