"""Add governance engine provenance and score audit log

Revision ID: 7aa6efe4bb79
Revises: 0013_framework_registry
Create Date: 2026-05-23 20:42:05.950454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7aa6efe4bb79'
down_revision: Union[str, Sequence[str], None] = '0013_framework_registry'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_audit_logs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('assessment_id', sa.CHAR(length=36), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=36), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('trigger_event', sa.String(length=255), nullable=False, comment="What triggered the score change (e.g., 'siem_provenance_update')."),
    sa.Column('affected_finding_ids', sqlite.JSON(), nullable=True, comment='JSON list of finding IDs that influenced this score change.'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_audit_logs_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('finding_provenance',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('finding_id', sa.CHAR(length=36), nullable=False, comment='FK to the finding this provenance covers (1-to-1).'),
    sa.Column('siem_alert_id', sa.String(length=255), nullable=True, comment='Unique alert/event ID from the source SIEM (Wazuh rule ID, Splunk SID, etc.).'),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw telemetry payload or manual evidence.'),
    sa.Column('evidence_payload_ref', sa.Text(), nullable=True, comment='Optional: S3/GCS URI or inline JSON snippet of the source evidence.'),
    sa.Column('verification_source', sa.Enum('SIEM_WAZUH', 'SIEM_SPLUNK', 'SIEM_ELASTIC', 'MANUAL_AUDIT', 'SELF_ATTESTED', name='verificationsource'), nullable=False, comment='Which system provided the verification evidence.'),
    sa.Column('verification_status', sa.Enum('SOC_VERIFIED', 'PROVISIONAL', 'CONTRADICTED', 'CONNECTION_ERROR', 'STALE_CONNECTION', name='provenancestatus'), nullable=False, comment='Current verification badge: SOC_VERIFIED, PROVISIONAL, or CONTRADICTED.'),
    sa.Column('rule_id_matched', sa.String(length=50), nullable=True, comment='The SIEM rule_id that was matched against the FrameworkMappingRegistry.'),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of when verification was performed.'),
    sa.Column('verified_by', sa.String(length=255), nullable=True, comment='Actor who triggered the verification (system/user UID).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_provenance_finding_id'), ['finding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_finding_provenance_siem_alert_id'), ['siem_alert_id'], unique=False)

    op.create_table('framework_mapping_registry',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('finding_id', sa.CHAR(length=36), nullable=False, comment='FK to the finding this mapping covers.'),
    sa.Column('framework_type', sa.Enum('NIST_CSF', 'NIST_AI_RMF', 'ISO_42001', 'MITRE_ATLAS', 'OWASP_LLM', 'SOC2', 'ISO_27001', name='frameworktype'), nullable=False, comment='The specific framework this mapping targets (e.g., NIST_AI_RMF).'),
    sa.Column('control_id', sa.String(length=100), nullable=False, comment="The control identifier within the framework (e.g., 'MAP 1.1', 'DE.CM-1')."),
    sa.Column('mapping_version', sa.String(length=20), nullable=False, comment='Semantic version of this mapping definition.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'framework_type', 'control_id', 'mapping_version', name='uq_framework_mapping_dynamic')
    )
    with op.batch_alter_table('framework_mapping_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_mapping_registry_control_id'), ['control_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mapping_registry_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_framework_mapping_registry_framework_type'), ['framework_type'], unique=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='assessmentstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))
        batch_op.drop_index(batch_op.f('ix_assessments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_schema_version'))
        batch_op.drop_index(batch_op.f('ix_assessments_status'))

    with op.batch_alter_table('audit_calendar', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('ix_audit_calendar_audit_date'))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'ACCEPTED', name='findingstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.drop_index(batch_op.f('ix_findings_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_findings_nist_function'))
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_status'))

    with op.batch_alter_table('framework_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_framework_registry_name'), ['name'], unique=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_assessment_id'))
        batch_op.drop_index(batch_op.f('ix_scores_domain_id'))

    with op.batch_alter_table('tech_stack_registry', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_stack_registry', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_assessment_id'), ['assessment_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('framework_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_registry_name'))

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_nist_function'), ['nist_function'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_assessment_id'), ['assessment_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'ACCEPTED', name='findingstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('severity',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('audit_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_calendar_audit_date'), ['audit_date'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_schema_version'), ['schema_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_organization_id'), ['organization_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='assessmentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'"))

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_assessment_id'), ['assessment_id'], unique=False)

    with op.batch_alter_table('framework_mapping_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_framework_mapping_registry_framework_type'))
        batch_op.drop_index(batch_op.f('ix_framework_mapping_registry_finding_id'))
        batch_op.drop_index(batch_op.f('ix_framework_mapping_registry_control_id'))

    op.drop_table('framework_mapping_registry')
    with op.batch_alter_table('finding_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_provenance_siem_alert_id'))
        batch_op.drop_index(batch_op.f('ix_finding_provenance_finding_id'))

    op.drop_table('finding_provenance')
    with op.batch_alter_table('score_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_score_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_score_audit_logs_assessment_id'))

    op.drop_table('score_audit_logs')
    # ### end Alembic commands ###
