"""Add technology discovery models

Revision ID: 845c6672fba3
Revises: 06057376e451
Create Date: 2026-06-04 23:07:57.846312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '845c6672fba3'
down_revision: Union[str, Sequence[str], None] = '06057376e451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_inventory',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('discovery_source', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technology_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technology_inventory_org_id'), ['org_id'], unique=False)

    op.create_table('discovered_assets',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('inventory_id', sa.CHAR(length=36), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('HOST', 'CLOUD_SERVICE', 'IAM', 'CONTAINER', 'NETWORK_DEVICE', name='assettype'), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('cloud_provider', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['technology_inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_assets_inventory_id'), ['inventory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_assets_org_id'), ['org_id'], unique=False)

    op.create_table('installed_products',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('asset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('installation_source', sa.String(length=255), nullable=True),
    sa.Column('eol_status', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['discovered_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installed_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installed_products_asset_id'), ['asset_id'], unique=False)

    op.create_table('evidence_sources',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_id', sa.CHAR(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('connector_name', sa.String(length=255), nullable=True),
    sa.Column('raw_evidence_hash', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['installed_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_sources_product_id'), ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentinel_simulations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('scenario_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('readiness_impact_score', sa.FLOAT(), nullable=False),
    sa.Column('weaknesses', sqlite.JSON(), nullable=True),
    sa.Column('missing_controls', sqlite.JSON(), nullable=True),
    sa.Column('simulation_context', sqlite.JSON(), nullable=True),
    sa.Column('executed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentinel_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_scenario'), ['scenario_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_org'), ['org_id'], unique=False)

    op.create_table('telemetry_evidence',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_reference', sa.VARCHAR(length=255), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('evidence_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('telemetry_verified', sa.BOOLEAN(), nullable=False),
    sa.Column('control_domain', sa.VARCHAR(length=100), nullable=True),
    sa.Column('framework_mapping', sa.VARCHAR(length=100), nullable=True),
    sa.Column('raw_event_reference', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['raw_event_reference'], ['telemetry_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_type'), ['evidence_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_domain'), ['control_domain'], unique=False)

    with op.batch_alter_table('evidence_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_sources_product_id'))

    op.drop_table('evidence_sources')
    with op.batch_alter_table('installed_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installed_products_asset_id'))

    op.drop_table('installed_products')
    with op.batch_alter_table('discovered_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_assets_org_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_assets_inventory_id'))

    op.drop_table('discovered_assets')
    with op.batch_alter_table('technology_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technology_inventory_org_id'))

    op.drop_table('technology_inventory')
    # ### end Alembic commands ###
