"""add_control_rule_registry

Revision ID: 88eaa0669c66
Revises: e1e4852cc868
Create Date: 2026-05-26 00:56:44.004282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88eaa0669c66'
down_revision: Union[str, Sequence[str], None] = 'e1e4852cc868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_rule_registry',
    sa.Column('id', sa.CHAR(length=36), nullable=False, comment='Surrogate UUID primary key.'),
    sa.Column('finding_rule_id', sa.String(length=100), nullable=False, comment="Deterministic rule identifier (e.g. 'DC-001', 'IV-002'). Matches the rule_id used by the FindingsEngine and SIEM forwarder."),
    sa.Column('nist_ai_rmf_control_id', sa.String(length=50), nullable=True, comment="NIST AI RMF control identifier (e.g. 'GOVERN-1.1', 'MAP-1.5')."),
    sa.Column('mitre_atlas_tactic_id', sa.String(length=50), nullable=True, comment="MITRE ATLAS tactic/technique ID (e.g. 'AML.TA0001', 'AML.T0043')."),
    sa.Column('mapping_version', sa.String(length=20), server_default='2026.1', nullable=False, comment="Semantic version of this mapping definition (e.g. '2026.1')."),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Soft-delete flag. Inactive mappings are excluded from resolution.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_rule_id', 'mapping_version', name='uq_control_rule_rule_version')
    )
    with op.batch_alter_table('control_rule_registry', schema=None) as batch_op:
        batch_op.create_index('ix_control_rule_active_rule', ['finding_rule_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_control_rule_registry_finding_rule_id'), ['finding_rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_rule_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_rule_registry_finding_rule_id'))
        batch_op.drop_index('ix_control_rule_active_rule')

    op.drop_table('control_rule_registry')
    # ### end Alembic commands ###
