"""governance_engine_phase1_2

Revision ID: 9417dc27ed92
Revises: 88eaa0669c66
Create Date: 2026-05-29 15:22:04.741448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '9417dc27ed92'
down_revision: Union[str, Sequence[str], None] = '88eaa0669c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wazuh_configs', schema=None) as batch_op:
        batch_op.alter_column('wazuh_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=app.db.types.EncryptedString(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wazuh_configs', schema=None) as batch_op:
        batch_op.alter_column('wazuh_api_key',
               existing_type=app.db.types.EncryptedString(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
