"""Add global lifecycle catalog

Revision ID: b88ca5746ac1
Revises: 845c6672fba3
Create Date: 2026-06-04 23:22:50.910773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b88ca5746ac1'
down_revision: Union[str, Sequence[str], None] = '845c6672fba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_software_catalog',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_family', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=100), nullable=True),
    sa.Column('current_lts_version', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_software_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_software_catalog_product_name'), ['product_name'], unique=True)

    op.create_table('software_versions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('catalog_id', sa.CHAR(length=36), nullable=False),
    sa.Column('version_name', sa.String(length=100), nullable=False),
    sa.Column('support_status', sa.String(length=50), nullable=False),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('eos_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['global_software_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('software_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_software_versions_catalog_id'), ['catalog_id'], unique=False)

    op.create_table('lifecycle_references',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('last_verified_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['software_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifecycle_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifecycle_references_version_id'), ['version_id'], unique=False)


    with op.batch_alter_table('software_catalog', schema=None) as batch_op:
        pass
        # batch_op.drop_index(batch_op.f('ix_software_catalog_org_id'))
        # batch_op.drop_index(batch_op.f('ix_software_catalog_org_product'))
        # batch_op.drop_index(batch_op.f('ix_software_catalog_product'))

    # op.drop_table('software_catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_catalog',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=255), nullable=True),
    sa.Column('product', sa.VARCHAR(length=255), nullable=False),
    sa.Column('current_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latest_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latest_release_date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('advisory_url', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('software_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_software_catalog_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_catalog_org_product'), ['org_id', 'product'], unique=False)
        batch_op.create_index(batch_op.f('ix_software_catalog_org_id'), ['org_id'], unique=False)



    with op.batch_alter_table('lifecycle_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_references_version_id'))

    op.drop_table('lifecycle_references')
    with op.batch_alter_table('software_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_software_versions_catalog_id'))

    op.drop_table('software_versions')
    with op.batch_alter_table('global_software_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_software_catalog_product_name'))

    op.drop_table('global_software_catalog')
    # ### end Alembic commands ###
