"""Add WazuhConfig table

Revision ID: e1e4852cc868
Revises: 7aa6efe4bb79
Create Date: 2026-05-24 00:06:20.764005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e4852cc868'
down_revision: Union[str, Sequence[str], None] = '7aa6efe4bb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wazuh_configs',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('org_id', sa.CHAR(length=36), nullable=False),
    sa.Column('wazuh_host', sa.String(length=255), nullable=False),
    sa.Column('wazuh_port', sa.Integer(), nullable=False),
    sa.Column('wazuh_api_key', sa.String(length=255), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wazuh_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wazuh_configs_org_id'), ['org_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wazuh_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wazuh_configs_org_id'))

    op.drop_table('wazuh_configs')
    # ### end Alembic commands ###
