"""
DriftEvent — Governance Drift Signal Tracking.

Records drift events detected by the governance engine when an
organization's posture deviates from its baseline. Each event carries
a signal type, severity, delta measurement, and an acknowledgement
workflow for operational triage.

Drift events are generated by the continuous monitoring pipeline and
surface in the dashboard as actionable alerts.
"""

import uuid

from sqlalchemy import (
    Column, String, Float, Boolean, DateTime, Text, Index,
    ForeignKey, JSON,
)
from sqlalchemy.dialects.sqlite import CHAR
from sqlalchemy.sql import func

from app.db.database import Base


class DriftEvent(Base):
    """Governance drift signal detected by the monitoring pipeline.

    Design Rationale:
      - signal_type classifies the drift (score_drop, control_gap, etc.).
      - delta quantifies the magnitude of drift from baseline.
      - baseline_id references the ScoreSnapshot or config baseline.
      - acknowledged workflow enables operational triage without deletion.
      - metadata_extra is a schemaless JSON bucket for signal-specific data.
    """

    __tablename__ = "drift_events"

    id = Column(
        CHAR(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        comment="Surrogate UUID primary key.",
    )
    org_id = Column(
        CHAR(36),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        comment="FK to the organization this drift event belongs to.",
    )
    signal_type = Column(
        String(100),
        nullable=False,
        comment="Classification of the drift signal (score_drop, control_gap, etc.).",
    )
    severity = Column(
        String(50),
        nullable=False,
        comment="Severity level of the drift event (critical, high, medium, low).",
    )
    title = Column(
        String(500),
        nullable=False,
        comment="Short human-readable title for the drift event.",
    )
    description = Column(
        Text,
        nullable=False,
        comment="Detailed description of the drift event and its context.",
    )
    delta = Column(
        Float,
        nullable=True,
        comment="Magnitude of drift from the baseline value.",
    )
    metadata_extra = Column(
        JSON,
        nullable=True,
        comment="Schemaless JSON bucket for signal-specific data.",
    )
    baseline_id = Column(
        String(255),
        nullable=True,
        comment="Reference to the baseline snapshot or config this drifted from.",
    )
    acknowledged = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether this drift event has been acknowledged by an operator.",
    )
    acknowledged_by = Column(
        String(255),
        nullable=True,
        comment="UID of the actor who acknowledged this drift event.",
    )
    acknowledged_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="UTC timestamp of when the drift event was acknowledged.",
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        comment="Row creation timestamp.",
    )

    __table_args__ = (
        Index("ix_drift_org_created", "org_id", "created_at"),
        Index("ix_drift_org_severity", "org_id", "severity"),
        Index("ix_drift_org_acknowledged", "org_id", "acknowledged"),
    )

    def __repr__(self) -> str:
        return (
            f"<DriftEvent(id={self.id}, type={self.signal_type!r}, "
            f"severity={self.severity!r}, ack={self.acknowledged})>"
        )
