"""
FindingProvenance — The Trust Anchor.

Immutable cryptographic provenance record linking a finding to its
source telemetry. Every verified finding carries a SHA-256 evidence_hash
that cryptographically binds it to the original SIEM alert or manual
audit evidence.

Architectural Invariant: The evidence_hash is computed deterministically
from the raw telemetry payload. It is NEVER generated by an LLM.

This model implements a 1-to-1 relationship with Finding.
One finding has at most one provenance record (the latest verification).
"""

import uuid
import enum

from sqlalchemy import Column, String, DateTime, ForeignKey, Enum as SQLEnum, Text
from sqlalchemy.dialects.sqlite import CHAR
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship, backref

from app.db.database import Base


class VerificationSource(str, enum.Enum):
    """Source of the verification evidence.

    Determines whether the finding was verified by an automated SIEM
    integration or a manual audit process.
    """
    SIEM_WAZUH = "SIEM_WAZUH"
    SIEM_SPLUNK = "SIEM_SPLUNK"
    SIEM_ELASTIC = "SIEM_ELASTIC"
    MANUAL_AUDIT = "MANUAL_AUDIT"
    SELF_ATTESTED = "SELF_ATTESTED"


class ProvenanceStatus(str, enum.Enum):
    """Verification status of the finding's evidence.

    SOC_VERIFIED:  SIEM telemetry confirms the finding.
    PROVISIONAL:   Self-attested only — no external corroboration.
    CONTRADICTED:  SIEM telemetry contradicts the self-reported data.
    """
    SOC_VERIFIED = "SOC_VERIFIED"
    PROVISIONAL = "PROVISIONAL"
    CONTRADICTED = "CONTRADICTED"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    STALE_CONNECTION = "STALE_CONNECTION"


class FindingProvenance(Base):
    """Immutable trust anchor for a finding.

    Design Rationale:
      - 1-to-1 with Finding (unique FK).
      - evidence_hash is the SHA-256 of the raw SIEM payload or manual
        evidence document, providing tamper-evident provenance.
      - siem_alert_id enables reverse-lookup back to the source SIEM.
      - The record is append-only in production: status changes create
        new provenance records with updated verified_at timestamps.
    """

    __tablename__ = "finding_provenance"

    id = Column(CHAR(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    finding_id = Column(
        CHAR(36),
        ForeignKey("findings.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="FK to the finding this provenance covers (1-to-1).",
    )

    # --- SIEM Evidence ---
    siem_alert_id = Column(
        String(255), nullable=True, index=True,
        comment="Unique alert/event ID from the source SIEM (Wazuh rule ID, Splunk SID, etc.).",
    )
    evidence_hash = Column(
        String(64), nullable=False,
        comment="SHA-256 hex digest of the raw telemetry payload or manual evidence.",
    )
    evidence_payload_ref = Column(
        Text, nullable=True,
        comment="Optional: S3/GCS URI or inline JSON snippet of the source evidence.",
    )

    # --- Classification ---
    verification_source = Column(
        SQLEnum(VerificationSource), nullable=False, default=VerificationSource.SELF_ATTESTED,
        comment="Which system provided the verification evidence.",
    )
    verification_status = Column(
        SQLEnum(ProvenanceStatus), nullable=False, default=ProvenanceStatus.PROVISIONAL,
        comment="Current verification badge: SOC_VERIFIED, PROVISIONAL, or CONTRADICTED.",
    )

    # --- Metadata ---
    rule_id_matched = Column(
        String(50), nullable=True,
        comment="The SIEM rule_id that was matched against the FrameworkMappingRegistry.",
    )
    verified_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
        comment="UTC timestamp of when verification was performed.",
    )
    verified_by = Column(
        String(255), nullable=True,
        comment="Actor who triggered the verification (system/user UID).",
    )

    # --- Timestamps ---
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # --- Relationships ---
    finding = relationship("Finding", backref=backref("provenance", uselist=False))

    def __repr__(self):
        return (
            f"<FindingProvenance(id={self.id}, finding={self.finding_id}, "
            f"status={self.verification_status}, hash={self.evidence_hash[:16]}...)>"
        )
